import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import Grid from '../components/Grid';
import Shop from '../components/Shop';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>coffee shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo1.svg" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Slider />
        <Grid />
        <Shop />
        <Footer />
      </main>
    </div>
  );
}
